version: "3"
services: 
    geth-bootnode:
        hostname: geth-bootnode
        environment:
            - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #nodekeyhex #where can i find this
        build:
            context: ./bootnode
        ports:
            - 30301:30301/udp
        networks:
            chainnet:
                ipv4_address: 172.25.0.101 # why??

    geth-dev-miner-1:
        hostname: geth-dev-miner-1
        depends_on:
            - geth-bootnode
        environment:
            - address=0x564a739aC1Fec5f4Ff0F9E3B5A8365E30B1b52C8 #address derived from the privatekey
            - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derive from the nodekeyhex
            - bootnodeIp=172.25.0.101 # why??
        build:
            context: ./miner
            args:
                privatekey: e7f8d262136ecfb1d605f379ba1beb2d7789fb5d0bd8c14725f6328887c48c87 #privatekey
                password: pass
        ports:
            - 8546:8545 # localhost:containerhost
        container_name: geth-miner-1
        volumes:
            - eth-data-1:/root/.ethash
        networks:
            chainnet:
                ipv4_address: 172.25.0.102 # why??
         
    geth-dev-miner-2:
        hostname: geth-dev-miner-2
        depends_on:
            - geth-bootnode
        environment:
            - address=0xa76e6e9B5ef94dd2A748216c42C060A90575D9F5 #address derived from the private key
            - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex
            - bootnodeIp=172.25.0.101
        build:
            context: ./miner
            args:
                privatekey: 9789913ab054cdd5bfae44b1dcd47126250e499be92447d05362151d218d6bff #privatekey
                password: pass
        container_name: geth-miner-2
        ports:
            - 8547:8545
        volumes:
            - eth-data-2:/root/.ethash
        networks:
            chainnet:
                ipv4_address: 172.25.0.103

    geth-dev-miner-3:
        hostname: geth-dev-miner-3
        depends_on:
            - geth-bootnode
        environment:
            - address=0xB55Fc240219d0F90F1D9207577F2Fe1DBcEC3752 #address derived from the private key
            - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex
            - bootnodeIp=172.25.0.101
        build:
            context: ./miner
            args:
                privatekey: 93fb85f9229458a7da6cbe996b9f0ae4cb2bb02914d76a651daa385a3410fafc #privatekey
                password: pass
        container_name: geth-miner-3
        ports:
            - 8548:8545
        volumes:
            - eth-data-3:/root/.ethash
        networks:
            chainnet:
                ipv4_address: 172.25.0.104

    geth-dev-node:
        hostname: geth-dev-node
        depends_on:
            - geth-dev-miner-1
        environment:
            - address=0x4977BA6Aa99867CBA74Ab64AE28046118f7150f5 #address derived from the private key
            - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex
            - bootnodeIp=172.25.0.101
        build:
            context: ./node
            args:
                privatekey: 1d204548ac620b457cfdcf64bdad7d8e70df1bd9b29a8108ffbc0805df5e0d79 #privatekey find a way to export this 
                password: pass
        container_name: geth-node
        ports:
            - 8545:8545
            - 8646:8646
        healthcheck:
            test: wget http://localhost:8545
            interval: 2s
            timeout: 5s
            retries: 30
        volumes:
            - eth-data-6:/root/.ethash
        networks:
            chainnet:
                ipv4_address: 172.25.0.110

networks:
    chainnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/24

volumes:
    eth-data-1:
    eth-data-2:
    eth-data-3:
    eth-data-4:
    eth-data-5:
    eth-data-6: